# Generated by Django 3.2.3 on 2021-05-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='poster_path',
            new_name='poster_title',
        ),
    ]
