# Generated by Django 3.2.3 on 2021-05-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
