# Generated by Django 3.2.3 on 2021-05-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_review_isequal'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isEqual',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
