# Generated by Django 3.2.3 on 2021-05-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_movie',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
