# Generated by Django 3.2.3 on 2021-05-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_like_movie_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_movie',
            name='liked',
        ),
    ]
