# Generated by Django 3.2.3 on 2021-05-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_like_movie_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_movie',
            name='movieid',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like_movie',
            name='poster',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
    ]
